# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Заголовок задачи')),
                ('description', models.CharField(max_length=400, verbose_name='Описанеие задачи')),
                ('star_date', models.DateField(verbose_name='Дата начала задачи')),
                ('deadline_date', models.DateField(verbose_name='Дата окончания задачи')),
                ('is_finished', models.BooleanField(default=False)),
                ('performer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Заголовок задачи')),
                ('description', models.CharField(max_length=400, verbose_name='Описанеие задачи')),
                ('star_date', models.DateField(verbose_name='Дата начала задачи')),
                ('deadline_date', models.DateField(verbose_name='Дата окончания задачи')),
                ('finish_rate', models.IntegerField(default=0, verbose_name='Процесс выполнения')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocs.Task'),
        ),
    ]
