# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='star_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
