# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0002_auto_20171114_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
