# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('LE', 'Leader')], default='US', max_length=2)),
            ],
        ),
    ]
