# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0008_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Заголовок задачи'),
        ),
    ]
