# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('registration', '0004_supervisedregistrationprofile'),
        ('ocs', '0014_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
