# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.CharField(blank=True, max_length=300, verbose_name='Содержимое')),
                ('image', models.FileField(blank=True, upload_to='news/%Y/%m/%d/')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
            },
        ),
    ]
