# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='new',
            name='own',
            field=models.BooleanField(default=True, verbose_name='Аналитическая?'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.FileField(blank=True, upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
