# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='periodic',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='module',
            name='state',
            field=models.CharField(choices=[('run', 'Running'), ('stop', 'Stopped')], default='stop', max_length=20),
        ),
    ]
