# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0002_auto_20171026_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='periodic',
            field=models.IntegerField(default=60),
        ),
    ]
