# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0002_remove_module_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Служебный?'),
        ),
    ]
