# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0003_module_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='last_executed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Последний запуск'),
            preserve_default=False,
        ),
    ]
