# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0003_auto_20171026_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='output_modules',
            field=models.ManyToManyField(blank=True, related_name='_module_output_modules_+', to='sod.Module'),
        ),
    ]
