# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0005_module_directory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='path',
        ),
    ]
