# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0006_remove_module_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='output_modules',
        ),
        migrations.AddField(
            model_name='dependancy',
            name='input_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sod.Module'),
        ),
        migrations.AddField(
            model_name='dependancy',
            name='output_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sod.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='output_modules_temp',
            field=models.ManyToManyField(blank=True, related_name='input_modules', through='sod.Dependancy', to='sod.Module'),
        ),
    ]
