# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0007_auto_20171102_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='output_modules_temp',
            new_name='output_modules',
        ),
    ]
