# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0008_auto_20171102_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя модуля')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Служебный?'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='module',
            name='extension',
            field=models.CharField(choices=[('m', 'Matlab'), ('py', 'Python'), ('exe', 'Execution')], max_length=10, verbose_name='Расширение'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='periodic',
            field=models.IntegerField(default=60, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='module',
            name='purpose',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображения'), ('music', 'Музыка'), ('crypto', 'Крипта')], max_length=100, verbose_name='Тип входящих файлов'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sended_files',
            field=models.IntegerField(default=0, verbose_name='Количество посланных файлов'),
        ),
        migrations.AlterField(
            model_name='module',
            name='state',
            field=models.CharField(choices=[('run', 'Running'), ('stop', 'Stopped')], default='stop', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='module',
            name='timeout',
            field=models.IntegerField(default=10, verbose_name='Таймаут'),
        ),
    ]
