# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sod', '0010_delete_servicemodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
    ]
